### ISSUE TITLE
预约报错  抢购不报错 怎么弄？

### ISSUE THREAD

**Issue by yanghonghao6789** [BlackWatch0/JDspyder#2]
[预约报错日志.txt](https://github.com/BlackWatch0/JDspyder/files/10242969/default.txt)
请大佬帮我kan看一下是什么原因

开始系统默认安装了python3.10  我删掉 装了3.8  
启动选择2 抢购没有报错 就是选1报错

**Comment by yanghonghao6789** [comment]
是不是还没到预约时间的原因报错，我去京东看了一下  每天上午10点开始预约  选择预约灰色的

**Comment by yanghonghao6789** [comment]
选择1 预约  二维码识别这里 手机点登录 之后就开始报错 看日志报的有个是登录获取信息有关  选择2 就没有这个错误  大佬排查一下  我是看不懂不过看信息报的是qrcode相关的错误

**Comment by yanghonghao6789** [comment]
2022-12-18 01:07:32,909 - 9060-MainThread - E:\抢茅台\JDspyder-main\maotai\jd_spider_requests.py[line:370] - INFO: 商品名称:京东(JD.COM)-正品低价、品质保障、配送及时、轻松购物！
--- Logging error ---
Traceback (most recent call last):
  File "E:\抢茅台\JDspyder-main\maotai\jd_spider_requests.py", line 348, in _reserve
    self.make_reserve()
  File "E:\抢茅台\JDspyder-main\maotai\jd_spider_requests.py", line 382, in make_reserve
    resp_json = parse_json(resp.text)
  File "E:\抢茅台\JDspyder-main\helper\jd_helper.py", line 66, in parse_json
    return json.loads(s[begin:end])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1081, in emit
    msg = self.format(record)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 925, in format
    return fmt.format(record)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 664, in format
    record.message = record.getMessage()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\抢茅台\JDspyder-main\main.py", line 26, in <module>
    jd_seckill.reserve()
  File "E:\抢茅台\JDspyder-main\maotai\jd_spider_requests.py", line 314, in new_func
    return func(self, *args, **kwargs)
  File "E:\抢茅台\JDspyder-main\maotai\jd_spider_requests.py", line 323, in reserve
    self._reserve()
  File "E:\抢茅台\JDspyder-main\maotai\jd_spider_requests.py", line 351, in _reserve
    logger.info('预约发生异常!', e)
Message: '预约发生异常!'
Arguments: (JSONDecodeError('Expecting value: line 1 column 1 (char 0)'),)

**Comment by bettermo** [comment]
你这个进去商品信息都没有出现，商品的sku_id没对吧
