### ISSUE TITLE
提示没有requests模块，是什么问题啊？

### ISSUE THREAD

**Issue by iamjimmycheng** [BlackWatch0/JDspyder#20]
Traceback (most recent call last):
  File ".\main.py", line 3, in <module>
    from maotai.jd_spider_requests import JdSeckill
  File "C:\Users\jimmy\Downloads\JDspyder-main\maotai\jd_spider_requests.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by BlackWatch0** [comment]
`pip install requests`
是不是没有安装环境

**Comment by iamjimmycheng** [comment]
哦，是的，之前是在windows下试的，后来换了ubuntu就可以运行了，但是抢购的时候提示获取链接失败是什么原因呢？
